# Generated by Django 4.2.6 on 2024-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contform_modelform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sqform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='modelform',
        ),
    ]
