# Generated by Django 4.2.6 on 2024-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sqform_delete_modelform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sqtable_cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Sqform',
        ),
    ]
