# Generated by Django 4.2.6 on 2024-04-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cartt_cartitem_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartt',
            new_name='Cart',
        ),
    ]
