# Generated by Django 4.2.6 on 2024-04-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_cartt_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
